BEGIN;
ALTER TABLE clients ADD COLUMN version INTEGER NOT NULL DEFAULT 1, ADD COLUMN deleted_at TIMESTAMPTZ(3);
ALTER TABLE loans ADD COLUMN version INTEGER NOT NULL DEFAULT 1, ADD COLUMN deleted_at TIMESTAMPTZ(3);
CREATE TABLE client_documents (
 id UUID PRIMARY KEY, client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
 kind VARCHAR(10) NOT NULL CHECK (kind IN ('PHOTO','INE')),
 file_name VARCHAR(200) NOT NULL, mime_type VARCHAR(50) NOT NULL,
 size INTEGER NOT NULL CHECK(size BETWEEN 1 AND 5242880), data BYTEA NOT NULL,
 UNIQUE(client_id,kind)
);
CREATE TABLE loan_revisions (
 id UUID PRIMARY KEY, loan_id UUID NOT NULL REFERENCES loans(id) ON DELETE RESTRICT,
 actor_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 action VARCHAR(15) NOT NULL, snapshot JSONB NOT NULL, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX loan_revisions_loan_id_idx ON loan_revisions(loan_id);
COMMIT;
