import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { ApiError } from '../services/auth';
import { getSettings, saveSettings } from '../services/administration';
import type { Settings } from '../services/administration';
import { frequencyLabels } from '../services/loans';
import './Administration.css';
import ThemePicker from '../theme/ThemePicker';
function SettingsForm({initial,onSaved,onReload,onSessionExpired}:{initial:Settings;onSaved:(s:Settings)=>void;onReload:()=>void;onSessionExpired:()=>void}) {
  const [name,setName]=useState(initial.businessName);const [interest,setInterest]=useState(String(initial.interestBps/100));const [count,setCount]=useState(String(initial.installmentCount));
  const [frequency,setFrequency]=useState(initial.frequency);const [interval,setInterval]=useState(String(initial.intervalDays));const [days,setDays]=useState(String(initial.firstPaymentAfterDays));
  const [phone,setPhone]=useState(initial.businessPhone);const [address,setAddress]=useState(initial.businessAddress);const [footer,setFooter]=useState(initial.receiptFooter);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const lock=useRef(false);
  async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;setError('');if(!/^\d+(\.\d{1,2})?$/.test(interest)){setError('El interés admite máximo dos decimales.');return;}lock.current=true;setBusy(true);
    try{onSaved(await saveSettings({...initial,businessName:name.trim(),businessPhone:phone.trim(),businessAddress:address.trim(),receiptFooter:footer.trim(),interestBps:Math.round(Number(interest)*100),installmentCount:Number(count),frequency,intervalDays:Number(interval),firstPaymentAfterDays:Number(days)}));}
    catch(err){if(err instanceof ApiError&&err.status===401)onSessionExpired();else setError(err instanceof ApiError?err.message:'No se pudo guardar la configuración.');}finally{lock.current=false;setBusy(false);}}
  return <form className="client-panel" onSubmit={e=>void submit(e)}><h3>Datos del negocio</h3><div className="form-field"><label htmlFor="settings-name">Nombre del negocio</label><input id="settings-name" required minLength={2} maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/><small>Se muestra en el menú lateral.</small></div><div className="client-form-grid"><div className="form-field"><label htmlFor="settings-phone">Teléfono del negocio (opcional)</label><input id="settings-phone" type="tel" maxLength={30} value={phone} disabled={busy} onChange={e=>setPhone(e.target.value)}/></div><div className="form-field"><label htmlFor="settings-address">Dirección del negocio (opcional)</label><input id="settings-address" maxLength={300} value={address} disabled={busy} onChange={e=>setAddress(e.target.value)}/></div></div><div className="form-field"><label htmlFor="settings-footer">Mensaje del comprobante (opcional)</label><input id="settings-footer" maxLength={300} value={footer} disabled={busy} onChange={e=>setFooter(e.target.value)}/><small>Estos datos aparecerán en los nuevos comprobantes. Los comprobantes ya emitidos conservan sus datos.</small></div><h3>Condiciones iniciales de los nuevos préstamos</h3><p>Estos valores llenan el formulario al abrir un nuevo préstamo. Puedes cambiarlos para cada cliente. Los préstamos registrados conservan sus condiciones.</p>
    <div className="client-form-grid"><div className="form-field"><label htmlFor="settings-interest">Interés total (%)</label><input id="settings-interest" type="number" required min="0" max="1000" step="0.01" value={interest} disabled={busy} onChange={e=>setInterest(e.target.value)}/><small>Porcentaje sobre el capital durante todo el préstamo.</small></div>
    <div className="form-field"><label htmlFor="settings-count">Número de pagos</label><input id="settings-count" type="number" required min="1" max="1000" step="1" value={count} disabled={busy} onChange={e=>setCount(e.target.value)}/></div>
    <div className="form-field"><label htmlFor="settings-frequency">Frecuencia</label><select id="settings-frequency" disabled={busy} value={frequency} onChange={e=>setFrequency(e.target.value as Settings['frequency'])}>{Object.entries(frequencyLabels).filter(([key])=>key!=='CUSTOM').map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></div>
    {frequency==='INTERVAL'&&<div className="form-field"><label htmlFor="settings-interval">Días entre pagos</label><input id="settings-interval" type="number" required min="1" max="365" step="1" value={interval} disabled={busy} onChange={e=>setInterval(e.target.value)}/></div>}
    <div className="form-field"><label htmlFor="settings-first">Días hasta el primer pago</label><input id="settings-first" type="number" required min="0" max="365" step="1" value={days} disabled={busy} onChange={e=>setDays(e.target.value)}/><small>Se cuentan a partir del día en que abres el formulario. Cero significa hoy.</small></div></div>
    <p className="admin-system-note">Moneda: pesos mexicanos (MXN) · Fechas operativas: Ciudad de México.</p>{error&&<p className="error-message" role="alert">{error}</p>}<div className="loan-actions"><button type="button" className="secondary-button" disabled={busy} onClick={onReload}>Recargar valores guardados</button><button className="primary-button" disabled={busy}>{busy?'Guardando…':'Guardar configuración'}</button></div>
  </form>;
}
export default function SettingsPage({onSessionExpired,onSaved}:{onSessionExpired:()=>void;onSaved:(s:Settings)=>void}) {
  const [data,setData]=useState<Settings|null>(null);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  useEffect(()=>{const c=new AbortController();void getSettings(c.signal).then(s=>{if(!c.signal.aborted)setData(s);}).catch(err=>{if(c.signal.aborted)return;if(err instanceof ApiError&&err.status===401)onSessionExpired();else setError(err instanceof ApiError?err.message:'No se pudo cargar la configuración.');});return()=>c.abort();},[revision,onSessionExpired]);
  function reload(){setData(null);setError('');setNotice('');setRevision(r=>r+1);}
  return <section className="clients-page administration-page"><header><h2>Configuración</h2><p>Personaliza el negocio y agiliza el registro de préstamos.</p></header><section className="client-panel"><h3>Apariencia</h3><ThemePicker/><p>El tema se aplica inmediatamente y se guarda en este navegador.</p></section>{notice&&<p className="client-notice" role="status">{notice}</p>}{error?<div><p className="error-message" role="alert">{error}</p><button className="secondary-button" onClick={reload}>Reintentar</button></div>:!data?<p role="status">Cargando configuración…</p>:<SettingsForm key={`${revision}-${data.version}`} initial={data} onSessionExpired={onSessionExpired} onReload={reload} onSaved={s=>{setData(s);onSaved(s);setNotice('Configuración guardada. Se aplicará a nuevos préstamos y comprobantes.');}}/>}</section>;
}
