import {useEffect,useState} from 'react';
import type {Client} from '../services/clients';
import {clientFile,deleteClientFile} from '../services/clients';
import type {UserRole} from '../services/auth';
import {ApiError} from '../services/auth';
export default function ClientFiles({client,role,onChanged,onSessionExpired}:{client:Client;role:UserRole;onChanged:(c:Client)=>void;onSessionExpired:()=>void}){
 const [photo,setPhoto]=useState<{version:number;url:string}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();let url='';if(client.documents.some(d=>d.kind==='PHOTO'))void clientFile(client.id,'PHOTO',c.signal).then(blob=>{if(!c.signal.aborted){url=URL.createObjectURL(blob);setPhoto({version:client.version,url});}}).catch(e=>{if(c.signal.aborted)return;if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError('No se pudo cargar la foto. Vuelve a abrir la ficha.');});return()=>{c.abort();if(url)URL.revokeObjectURL(url);};},[client.id,client.version,client.documents,onSessionExpired]);
 async function action(kind:'PHOTO'|'INE',remove=false){if(busy)return;if(remove&&!window.confirm('¿Quitar este archivo del expediente?'))return;setBusy(true);setError('');try{if(remove)onChanged(await deleteClientFile(client,kind));else{const blob=await clientFile(client.id,kind);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=client.documents.find(d=>d.kind===kind)?.fileName??'documento';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError(e instanceof ApiError?e.message:'No se pudo completar la operación.');}finally{setBusy(false);}}
 return <div className="client-files">{photo?.version===client.version&&<img className="client-photo" src={photo.url} alt={`Fotografía de ${client.fullName}`}/>}<div><h4>Expediente opcional</h4>{client.documents.length===0&&<p>Sin archivos adjuntos.</p>}{client.documents.filter(d=>d.kind==='PHOTO'||role==='ADMIN').map(d=><div className="client-file-row" key={d.kind}><span>{d.kind==='PHOTO'?'Fotografía':'INE'} · {d.fileName}</span><button className="secondary-button" disabled={busy} onClick={()=>void action(d.kind)}>Descargar</button>{role==='ADMIN'&&!client.deletedAt&&<button className="secondary-button" disabled={busy} onClick={()=>void action(d.kind,true)}>Quitar</button>}</div>)}{role==='ADMIN'&&<p>Para agregar o reemplazar archivos, selecciona Editar cliente.</p>}{error&&<p role="alert" className="error-message">{error}</p>}</div></div>;
}
