import Dialog from '../components/Dialog';
import ResponsiveTable from '../components/ResponsiveTable';
import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {ApiError} from '../services/auth';
import type {UserRole} from '../services/auth';
import {archiveClient,createClient,getClient,listClients,updateClient,uploadClientFile} from '../services/clients';
import type {Client,ClientsResponse,CreateClientInput} from '../services/clients';
import ClientFiles from './ClientFiles';
import './ClientsPage.css';
const blank:CreateClientInput={fullName:'',phone:'',address:'',notes:'',referenceName:'',referencePhone:''};
const fields=[{key:'fullName',label:'Nombre completo',max:150,required:true},{key:'phone',label:'Teléfono',max:30,required:true},{key:'address',label:'Dirección',max:500,required:true},{key:'referenceName',label:'Nombre de referencia',max:150,required:false},{key:'referencePhone',label:'Teléfono de referencia',max:30,required:false},{key:'notes',label:'Notas',max:5000,required:false}] as const;
const colors={GREEN:'Verde · Puntual',YELLOW:'Amarillo · Atraso leve',RED:'Rojo · Atraso importante',GRAY:'Gris · Sin historial reciente'};
const message=(e:unknown)=>e instanceof ApiError?e.message:'No se pudo completar la operación. Intenta nuevamente.';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
function ClientEditor({initial,onSaved,onCancel,onSessionExpired}:{initial:Client|null;onSaved:(c:Client)=>void;onCancel:()=>void;onSessionExpired:()=>void}){
 const [stored,setStored]=useState(initial);const [form,setForm]=useState<CreateClientInput>(initial?Object.fromEntries(fields.map(f=>[f.key,initial[f.key]??''])) as unknown as CreateClientInput:blank);
 const [active,setActive]=useState(initial?.isActive??true);const [photo,setPhoto]=useState<File|null>(null);const [ine,setIne]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const lock=useRef(false);
 async function save(e:FormEvent){e.preventDefault();if(lock.current)return;setError('');if([photo,ine].some(f=>f&&f.size>5*1024*1024)){setError('Cada archivo debe pesar como máximo 5 MB.');return;}lock.current=true;setBusy(true);let saved:Client|null=null;
  try{let client=stored?await updateClient(stored.id,form,stored.version,active):await createClient(form);saved=client;setStored(client);
   if(photo){client=await uploadClientFile(client,'PHOTO',photo);setStored(client);setPhoto(null);}
   if(ine){client=await uploadClientFile(client,'INE',ine);setStored(client);setIne(null);}
   onSaved(client);
  }catch(e){if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError((saved?'Los datos del cliente se guardaron. Falta adjuntar un archivo: ':'')+message(e));}finally{lock.current=false;setBusy(false);}}
 return <Dialog label={stored?"Editar cliente":"Registrar cliente"} onClose={onCancel} busy={busy}><form className="client-panel" onSubmit={e=>void save(e)}><div className="clients-heading"><h3>{stored?'Editar cliente':'Registrar cliente'}</h3><button type="button" className="secondary-button" disabled={busy} onClick={onCancel}>Cancelar</button></div><p>Nombre, teléfono y dirección son obligatorios. Fotografía e INE son opcionales.</p><div className="client-form-grid">{fields.map(f=><div className="form-field" key={f.key}><label htmlFor={'client-'+f.key}>{f.label}{f.required?' *':' (opcional)'}</label>{f.key==='notes'||f.key==='address'?<textarea id={'client-'+f.key} required={f.required} maxLength={f.max} value={form[f.key]??''} disabled={busy} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input id={'client-'+f.key} type={f.key.toLowerCase().includes('phone')?'tel':'text'} required={f.required} maxLength={f.max} value={form[f.key]??''} disabled={busy} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</div>)}
 {stored&&<div className="form-field"><label htmlFor="client-active">Estado</label><select id="client-active" value={String(active)} disabled={busy} onChange={e=>setActive(e.target.value==='true')}><option value="true">Activo</option><option value="false">Inactivo</option></select></div>}
 <div className="form-field"><label htmlFor="client-photo">Fotografía (opcional)</label><input id="client-photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>setPhoto(e.target.files?.[0]??null)}/><small>JPG, PNG o WebP · Hasta 5 MB. Al seleccionar una nueva, reemplazas la anterior.</small></div>
 <div className="form-field"><label htmlFor="client-ine">INE (opcional)</label><input id="client-ine" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>setIne(e.target.files?.[0]??null)}/><small>Imagen o PDF con las caras de la identificación · Hasta 5 MB.</small></div></div>{error&&<p role="alert" className="error-message">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'Guardando…':'Guardar cliente'}</button></form></Dialog>;
}
export default function ClientsPage({role,onSessionExpired,refreshVersion=0,active=true,initialTraffic='ALL',onChanged}:{role:UserRole;onSessionExpired:()=>void;refreshVersion?:number;active?:boolean;initialTraffic?:string;onChanged?:()=>void}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState({search:'',page:1,revision:0,traffic:initialTraffic,archived:false});const [data,setData]=useState<ClientsResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [editor,setEditor]=useState<{client:Client|null}|null>(null);const [selected,setSelected]=useState<Client|null>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!active)return;const c=new AbortController();void listClients({...filter,signal:c.signal}).then(r=>{if(!c.signal.aborted){setData(r);setError('');setSelected(old=>old?r.items.find(i=>i.id===old.id)??null:null);}}).catch(e=>{if(c.signal.aborted)return;if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError(message(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[filter,active,refreshVersion,onSessionExpired]);
 function refresh(changes:Partial<typeof filter>={}){setLoading(true);setError('');setFilter(f=>({...f,...changes,revision:f.revision+1}));}
 async function open(id:string,edit=false){if(busy)return;setBusy(true);setError('');try{const c=await getClient(id);if(edit)setEditor({client:c});else setSelected(c);}catch(e){if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError(message(e));}finally{setBusy(false);}}
 async function remove(c:Client){if(busy)return;const restore=!!c.deletedAt;if(!window.confirm(restore?'¿Restaurar este cliente?':'¿Eliminar al cliente del directorio? Sus préstamos y cobros se conservan. Podrás restaurarlo desde Eliminados.'))return;setBusy(true);try{await archiveClient(c,restore);setSelected(null);setNotice(restore?'Cliente restaurado.':'Cliente enviado a Eliminados.');onChanged?.();refresh();}catch(e){if(e instanceof ApiError&&e.status===401)onSessionExpired();else setError(message(e));}finally{setBusy(false);}}
 return <section className="clients-page"><header className="clients-heading"><div><span className="eyebrow">DIRECTORIO Y PUNTUALIDAD</span><h2>{initialTraffic==='LATE'?'Clientes con atrasos':'Clientes'}</h2><p>Datos, expediente y comportamiento de pago.</p></div>{role==='ADMIN'&&!editor&&<button className="primary-button" onClick={()=>{setEditor({client:null});setNotice('');}}>Nuevo cliente</button>}</header>
 <details className="client-risk-guide"><summary>Cómo se calcula el semáforo</summary><p>Verde: sin atrasos observados. Amarillo: de 1 a 7 días. Rojo: más de 7 días. Se considera el mayor atraso pendiente y los pagos tardíos de los últimos 90 días, incluso si después se liquidaron. Las cuotas parcialmente pagadas siguen vencidas. Gris: sin pagos o vencimientos recientes para evaluar. El color es informativo y no decide automáticamente si se concede un préstamo.</p><p>La fecha de hoy todavía no cuenta como atraso. Un préstamo eliminado conserva sus atrasos recientes en el historial, aunque deja de formar parte de cobranza.</p></details>
 {notice&&<p className="client-notice" role="status">{notice}</p>}{editor&&role==='ADMIN'&&<ClientEditor key={editor.client?.id??'new'} initial={editor.client} onSessionExpired={onSessionExpired} onCancel={()=>setEditor(null)} onSaved={c=>{setEditor(null);setSelected(c);setNotice('Cliente guardado correctamente.');onChanged?.();refresh({page:1});}}/>}
 <form className="client-search" onSubmit={e=>{e.preventDefault();refresh({search:query.trim(),page:1});}}><div className="form-field"><label htmlFor="client-search">Buscar por nombre o teléfono</label><input id="client-search" type="search" maxLength={150} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="form-field"><label htmlFor="client-traffic">Semáforo</label><select id="client-traffic" value={filter.traffic} onChange={e=>refresh({traffic:e.target.value,page:1})}><option value="ALL">Todos</option><option value="LATE">Con atrasos (amarillo / rojo)</option>{Object.entries(colors).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className="form-field"><label htmlFor="client-archive">Directorio</label><select id="client-archive" value={String(filter.archived)} onChange={e=>refresh({archived:e.target.value==='true',page:1})}><option value="false">Clientes actuales</option><option value="true">Eliminados</option></select></div><button className="secondary-button">Buscar</button></form>
 {loading&&<p role="status">Cargando clientes…</p>}{error&&<div><p role="alert" className="error-message">{error}</p><button className="secondary-button" onClick={()=>refresh()}>Reintentar</button></div>}
 {!loading&&!error&&data&&<><p>{data.pagination.total} clientes encontrados</p>{data.items.length===0?<p className="client-panel">No hay clientes que coincidan con los filtros.</p>:<div className="client-table-wrap"><ResponsiveTable className="client-table"><thead><tr><th>Nombre</th><th>Teléfono</th><th>Semáforo</th><th>Vencido</th><th>Estado</th><th>Ficha</th></tr></thead><tbody>{data.items.map(c=><tr key={c.id}><td>{c.fullName}</td><td>{c.phone}</td><td><span className={'client-risk '+c.risk.color.toLowerCase()}>{colors[c.risk.color]}</span></td><td>{money(c.risk.overdueCents)}</td><td>{c.deletedAt?'Eliminado':c.isActive?'Activo':'Inactivo'}</td><td><button className="secondary-button" disabled={busy} onClick={()=>void open(c.id)} aria-label={'Ver ficha de '+c.fullName}>Ver ficha</button></td></tr>)}</tbody></ResponsiveTable></div>}<nav className="client-pagination"><button className="secondary-button" disabled={filter.page<=1} onClick={()=>refresh({page:filter.page-1})}>Anterior</button><span>Página {filter.page} de {Math.max(1,data.pagination.totalPages)}</span><button className="secondary-button" disabled={filter.page>=data.pagination.totalPages} onClick={()=>refresh({page:filter.page+1})}>Siguiente</button></nav></>}
 {selected&&<Dialog label="Ficha del cliente" onClose={()=>setSelected(null)} busy={busy||!!editor}><section className="client-panel" aria-label="Ficha del cliente"><div className="clients-heading"><h3>{selected.fullName}</h3><button className="secondary-button" onClick={()=>setSelected(null)}>Cerrar ficha</button></div><p><span className={'client-risk '+selected.risk.color.toLowerCase()}>{colors[selected.risk.color]}</span></p><p>Atraso pendiente máximo: {selected.risk.currentDays} días · Atraso histórico reciente: {selected.risk.historyDays} días · Saldo vencido: {money(selected.risk.overdueCents)}</p><ClientFiles client={selected} role={role} onSessionExpired={onSessionExpired} onChanged={c=>{setSelected(c);refresh();}}/><dl>{fields.filter(f=>f.key!=='fullName').map(f=><div key={f.key}><dt>{f.label}</dt><dd>{selected[f.key]||'Sin registrar'}</dd></div>)}</dl>{role==='ADMIN'&&<div className="loan-actions">{!selected.deletedAt&&<button className="secondary-button" disabled={busy||!!editor} onClick={()=>void open(selected.id,true)}>Editar cliente</button>}<button className="secondary-button" disabled={busy||!!editor} onClick={()=>void remove(selected)}>{selected.deletedAt?'Restaurar cliente':'Eliminar cliente'}</button></div>}</section></Dialog>}
 </section>;
}
